import enum


class CRAWLER_STATUS(enum.Enum):
    S_CLOSED = 0
    S_RUNNING = 1
    S_PAUSE = 2
    S_STOP = 3
    S_BACKUP = 4

class CRAWL_CONTROLLER_COMMANDS(enum.Enum):
    S_RUN_GENERAL_CRAWLER = 1
    S_RUN_TOPIC_CLASSIFIER_CRAWLER = 2
    S_LOAD_TOPIC_CLASSIFIER_DATASET = 3

class CRAWL_MODEL_COMMANDS(enum.Enum):
    S_SAVE_BACKUP_URL = 1
    S_GET_HOST_URL = 2
    S_INSERT_URL = 3
    S_GET_SUB_URL = 4
    S_CRAWL_FINISHED_STATUS = 5

class CLASSIFIER:
    S_CLASSIFIER_LABEL = "CLASSIFIER"
    S_CLASSIFIER_URL= "URL"
    S_CLASSIFIER_NEWS = "news"
    S_CLASSIFIER_BUSINESS = "business"
    S_CLASSIFIER_ADULT = "adult"

class DOCUMENT_INDEX(enum.Enum):
    S_HOST = "m_host"


